# Generated by Django 5.1.4 on 2024-12-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_choice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'text')},
        ),
    ]
